### PR TITLE
Replaced the old banner with the new banner (st-sd-banner)

### PR DESCRIPTION
**Pull request by nattcodes**
Replaced the old banner with the new banner (st-sd-banner)

### CODE REVIEW

**Review by cerver1 — COMMENTED** [review]
Please include a screenshot of the changes made.

**Comment by nattcodes** [comment]
> Please include a screenshot of the changes made.

Replaced the old banner with the new banner (st-sd-banner);

Screenshot (102)


Fixed: Mobile hamburger menu on the right side;

Screenshot (103)
Screenshot (100)
Screenshot (101)

**Comment by cerver1** [comment]
Thank you for your PR, @nattcodes. I should have made my comment clearer. Please share images of the ST-SD site showing the changes you made(i.e. an image of the site with the new hamburger position and an image of the site with the new banner).

**Comment by nattcodes** [comment]
> Thank you for your PR, @nattcodes. I should have made my comment clearer. Please share images of the ST-SD site showing the changes you made(i.e. an image of the site with the new hamburger position and an image of the site with the new banner).

Screenshot (107)
Screenshot (105)
Screenshot (106)

**Review by cerver1 — APPROVED** [review]
Thank you for your quick changes to the PR!

**Pull request merged**
